apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default (printf "%s-karl" .Release.Name) .Values.fullnameOverride }}-config
  labels:
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  karl-defaults.json: |
{{ dict "active_model" .Values.config.activeModel "headless" true "websocket_port" .Values.service.port | toPrettyJson | indent 4 }}
  model_registry.json: |
{{ .Values.config.modelRegistry | toPrettyJson | indent 4 }}
