{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ default (printf "%s-karl" .Release.Name) .Values.fullnameOverride }}
  labels:
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
{{- with .Values.ingress.tls }}
  tls:
{{ toYaml . | indent 4 }}
{{- end }}
  rules:
{{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
{{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ default (printf "%s-karl" $.Release.Name) $.Values.fullnameOverride }}
                port:
                  number: {{ $.Values.service.port }}
{{- end }}
{{- end }}
{{- end }}
