{{- if not .Values.bridge.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-karl" .Release.Name) .Values.fullnameOverride }}-bridge
  labels:
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
stringData:
  {{ .Values.bridge.secretKey }}: {{ .Values.bridge.token | quote }}
{{- end }}
