apiVersion: v1
kind: Service
metadata:
  name: {{ default (printf "%s-karl" .Release.Name) .Values.fullnameOverride }}
  labels:
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - name: wss
      port: {{ .Values.service.port }}
      targetPort: wss
      protocol: TCP
