apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karl-data
  labels:
    app.kubernetes.io/name: karl
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 100Gi
